package xyz.ankitgrai.taskplanner.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * 7 preset color themes, each providing light and dark Material3 color slots.
 */
enum class ColorTheme(
    val displayName: String,
    val previewColor: Color, // The swatch color shown in settings
    // Light scheme
    val lightPrimary: Color,
    val lightOnPrimary: Color,
    val lightPrimaryContainer: Color,
    val lightOnPrimaryContainer: Color,
    val lightSecondary: Color,
    val lightOnSecondary: Color,
    val lightSecondaryContainer: Color,
    val lightOnSecondaryContainer: Color,
    val lightTertiary: Color,
    val lightOnTertiary: Color,
    // Dark scheme
    val darkPrimary: Color,
    val darkOnPrimary: Color,
    val darkPrimaryContainer: Color,
    val darkOnPrimaryContainer: Color,
    val darkSecondary: Color,
    val darkOnSecondary: Color,
    val darkSecondaryContainer: Color,
    val darkOnSecondaryContainer: Color,
    val darkTertiary: Color,
    val darkOnTertiary: Color,
) {
    Blue(
        displayName = "Blue",
        previewColor = Color(0xFF1565C0),
        lightPrimary = Color(0xFF1565C0),
        lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFFD1E4FF),
        lightOnPrimaryContainer = Color(0xFF001D36),
        lightSecondary = Color(0xFF26A69A),
        lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFCEE5FF),
        lightOnSecondaryContainer = Color(0xFF001D33),
        lightTertiary = Color(0xFF6B5778),
        lightOnTertiary = Color(0xFFFFFFFF),
        darkPrimary = Color(0xFF90CAF9),
        darkOnPrimary = Color(0xFF003258),
        darkPrimaryContainer = Color(0xFF00497D),
        darkOnPrimaryContainer = Color(0xFFD1E4FF),
        darkSecondary = Color(0xFF80CBC4),
        darkOnSecondary = Color(0xFF003547),
        darkSecondaryContainer = Color(0xFF004D65),
        darkOnSecondaryContainer = Color(0xFFBDE9FF),
        darkTertiary = Color(0xFFD7BDE5),
        darkOnTertiary = Color(0xFF3B2948),
    ),

    Purple(
        displayName = "Purple",
        previewColor = Color(0xFF6750A4),
        lightPrimary = Color(0xFF6750A4),
        lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFFEADDFF),
        lightOnPrimaryContainer = Color(0xFF21005D),
        lightSecondary = Color(0xFF625B71),
        lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFE8DEF8),
        lightOnSecondaryContainer = Color(0xFF1D192B),
        lightTertiary = Color(0xFF7D5260),
        lightOnTertiary = Color(0xFFFFFFFF),
        darkPrimary = Color(0xFFD0BCFF),
        darkOnPrimary = Color(0xFF381E72),
        darkPrimaryContainer = Color(0xFF4F378B),
        darkOnPrimaryContainer = Color(0xFFEADDFF),
        darkSecondary = Color(0xFFCCC2DC),
        darkOnSecondary = Color(0xFF332D41),
        darkSecondaryContainer = Color(0xFF4A4458),
        darkOnSecondaryContainer = Color(0xFFE8DEF8),
        darkTertiary = Color(0xFFEFB8C8),
        darkOnTertiary = Color(0xFF492532),
    ),

    Green(
        displayName = "Green",
        previewColor = Color(0xFF2E7D32),
        lightPrimary = Color(0xFF2E7D32),
        lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFFA8F0AB),
        lightOnPrimaryContainer = Color(0xFF002106),
        lightSecondary = Color(0xFF52634F),
        lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFD5E8CF),
        lightOnSecondaryContainer = Color(0xFF101F10),
        lightTertiary = Color(0xFF386569),
        lightOnTertiary = Color(0xFFFFFFFF),
        darkPrimary = Color(0xFF81C784),
        darkOnPrimary = Color(0xFF00390E),
        darkPrimaryContainer = Color(0xFF005319),
        darkOnPrimaryContainer = Color(0xFFA8F0AB),
        darkSecondary = Color(0xFFBACCB4),
        darkOnSecondary = Color(0xFF253424),
        darkSecondaryContainer = Color(0xFF3B4B39),
        darkOnSecondaryContainer = Color(0xFFD5E8CF),
        darkTertiary = Color(0xFFA0CFD3),
        darkOnTertiary = Color(0xFF00363A),
    ),

    Red(
        displayName = "Coral",
        previewColor = Color(0xFFC62828),
        lightPrimary = Color(0xFFC62828),
        lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFFFFDAD5),
        lightOnPrimaryContainer = Color(0xFF410002),
        lightSecondary = Color(0xFF775653),
        lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFFFDAD5),
        lightOnSecondaryContainer = Color(0xFF2C1513),
        lightTertiary = Color(0xFF705C2E),
        lightOnTertiary = Color(0xFFFFFFFF),
        darkPrimary = Color(0xFFEF9A9A),
        darkOnPrimary = Color(0xFF690005),
        darkPrimaryContainer = Color(0xFF93000A),
        darkOnPrimaryContainer = Color(0xFFFFDAD5),
        darkSecondary = Color(0xFFE7BDB8),
        darkOnSecondary = Color(0xFF442927),
        darkSecondaryContainer = Color(0xFF5D3F3C),
        darkOnSecondaryContainer = Color(0xFFFFDAD5),
        darkTertiary = Color(0xFFDFC08D),
        darkOnTertiary = Color(0xFF3E2E05),
    ),

    Teal(
        displayName = "Teal",
        previewColor = Color(0xFF00796B),
        lightPrimary = Color(0xFF00796B),
        lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFF74F8E3),
        lightOnPrimaryContainer = Color(0xFF002019),
        lightSecondary = Color(0xFF4A635E),
        lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFCDE8E1),
        lightOnSecondaryContainer = Color(0xFF06201B),
        lightTertiary = Color(0xFF446179),
        lightOnTertiary = Color(0xFFFFFFFF),
        darkPrimary = Color(0xFF4DB6AC),
        darkOnPrimary = Color(0xFF00382E),
        darkPrimaryContainer = Color(0xFF005144),
        darkOnPrimaryContainer = Color(0xFF74F8E3),
        darkSecondary = Color(0xFFB1CCC5),
        darkOnSecondary = Color(0xFF1C3530),
        darkSecondaryContainer = Color(0xFF334B46),
        darkOnSecondaryContainer = Color(0xFFCDE8E1),
        darkTertiary = Color(0xFFAAC7E2),
        darkOnTertiary = Color(0xFF123348),
    ),

    Orange(
        displayName = "Orange",
        previewColor = Color(0xFFE65100),
        lightPrimary = Color(0xFFE65100),
        lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFFFFDBCF),
        lightOnPrimaryContainer = Color(0xFF380D00),
        lightSecondary = Color(0xFF77574C),
        lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFFFDBCF),
        lightOnSecondaryContainer = Color(0xFF2C160E),
        lightTertiary = Color(0xFF695E2F),
        lightOnTertiary = Color(0xFFFFFFFF),
        darkPrimary = Color(0xFFFFB74D),
        darkOnPrimary = Color(0xFF5B1A00),
        darkPrimaryContainer = Color(0xFF802800),
        darkOnPrimaryContainer = Color(0xFFFFDBCF),
        darkSecondary = Color(0xFFE7BEAF),
        darkOnSecondary = Color(0xFF442A20),
        darkSecondaryContainer = Color(0xFF5D4035),
        darkOnSecondaryContainer = Color(0xFFFFDBCF),
        darkTertiary = Color(0xFFD4C68D),
        darkOnTertiary = Color(0xFF383005),
    ),

    Pink(
        displayName = "Pink",
        previewColor = Color(0xFFAD1457),
        lightPrimary = Color(0xFFAD1457),
        lightOnPrimary = Color(0xFFFFFFFF),
        lightPrimaryContainer = Color(0xFFFFD9E2),
        lightOnPrimaryContainer = Color(0xFF3E001D),
        lightSecondary = Color(0xFF74565F),
        lightOnSecondary = Color(0xFFFFFFFF),
        lightSecondaryContainer = Color(0xFFFFD9E2),
        lightOnSecondaryContainer = Color(0xFF2B151C),
        lightTertiary = Color(0xFF7C5635),
        lightOnTertiary = Color(0xFFFFFFFF),
        darkPrimary = Color(0xFFF48FB1),
        darkOnPrimary = Color(0xFF5E1132),
        darkPrimaryContainer = Color(0xFF7B2949),
        darkOnPrimaryContainer = Color(0xFFFFD9E2),
        darkSecondary = Color(0xFFE2BDC6),
        darkOnSecondary = Color(0xFF422931),
        darkSecondaryContainer = Color(0xFF5B3F47),
        darkOnSecondaryContainer = Color(0xFFFFD9E2),
        darkTertiary = Color(0xFFE5BF91),
        darkOnTertiary = Color(0xFF42290A),
    );

    companion object {
        fun fromKey(key: String): ColorTheme {
            return entries.find { it.name.equals(key, ignoreCase = true) } ?: Blue
        }
    }
}
